---
title: "Pilot3_changed_format_wording6and5"
author: "Yochai Shavit"
date: "September 8, 2016"
output: html_document
---

## Don't forget to reverse-code all sm_3's !!! ##

```{r load packages}
library(knitr)
library(GGally)
library(ggplot2)
library(psych)
library(tidyr)
library(dplyr)
library(car)
library(effsize)
## scale.means function ##
scale.means= function (df, ..., na.rm=FALSE) {
  vars=unlist(list(...))
  mean_vars=rowMeans(df[,vars], na.rm=na.rm)
  return(mean_vars)
}

```

```{r load data- do not forget to recode sm3s}
volbank3=read.csv("Pilot3_reverse_codeSM3!!.csv")

```

```{r reverse code all sm3s}
#Vol 2
volbank3$vol2_sm3=Recode(volbank3$vol2_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 5
volbank3$vol5_sm3=Recode(volbank3$vol5_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 6
volbank3$vol6_sm3=Recode(volbank3$vol6_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 7
volbank3$vol7_sm3=Recode(volbank3$vol7_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 13
volbank3$vol13_sm3=Recode(volbank3$vol13_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 16
volbank3$vol16_sm3=Recode(volbank3$vol16_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)

#Vol 18
volbank3$vol18_sm3=Recode(volbank3$vol18_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 19
volbank3$vol19_sm3=Recode(volbank3$vol19_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 20
volbank3$vol20_sm3=Recode(volbank3$vol20_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
#Vol 22
volbank3$vol22_sm3=Recode(volbank3$vol22_sm3, "'5'='1';
                         '4'='2';
                         '3'='3';
                         '2'='4';
                         '13'='5';",
                         as.numeric.result = TRUE)
```

```{r create longform dataset}
#Long-form repeated measures variables

#Likely
Pilot3_lnglik=reshape(volbank3,
                   varying = c( "vol2_likely","vol5_likely","vol6_likely","vol7_likely","vol13_likely","vol16_likely","vol18_likely","vol19_likely","vol20_likely", "vol22_likely"), v.names=c("likely"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm1
Pilot3_lngtm1=reshape(volbank3,
                   varying = c("vol2_tm1", "vol5_tm1", "vol6_tm1","vol7_tm1","vol13_tm1","vol16_tm1","vol18_tm1","vol19_tm1","vol20_tm1", "vol22_tm1"), v.names=c("tm1"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm2
Pilot3_lngtm2=reshape(volbank3,
                   varying = c("vol2_tm2", "vol5_tm2", "vol6_tm2","vol7_tm2","vol13_tm2","vol16_tm2","vol18_tm2","vol19_tm2","vol20_tm2", "vol22_tm2"), v.names=c("tm2"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm3
Pilot3_lngtm3=reshape(volbank3,
                   varying = c("vol2_tm3", "vol5_tm3", "vol6_tm3","vol7_tm3","vol13_tm3","vol16_tm3","vol18_tm3","vol19_tm3","vol20_tm3","vol22_tm3"), v.names=c("tm3"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm1
Pilot3_lngsm1=reshape(volbank3,
                   varying = c("vol2_sm1", "vol5_sm1", "vol6_sm1","vol7_sm1","vol13_sm1","vol16_sm1","vol18_sm1","vol19_sm1","vol20_sm1", "vol22_sm1"), v.names=c("sm1"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm2
Pilot3_lngsm2=reshape(volbank3,
                   varying = c("vol2_sm2", "vol5_sm2", "vol6_sm2","vol7_sm2","vol13_sm2","vol16_sm2","vol18_sm2","vol19_sm2","vol20_sm2", "vol22_sm2"), v.names=c("sm2"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm3
Pilot3_lngsm3=reshape(volbank3,
                   varying = c("vol2_sm3", "vol5_sm3", "vol6_sm3","vol7_sm3","vol13_sm3","vol16_sm3","vol18_sm3","vol19_sm3","vol20_sm3", "vol22_sm3"), v.names=c("sm3"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#Difficulty
Pilot3_lngdiff=reshape(volbank3,
                   varying = c( "vol2_diff","vol5_diff","vol6_diff","vol7_diff","vol13_diff","vol16_diff","vol18_diff","vol19_diff","vol20_diff", "vol22_diff"), v.names=c("difficult"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#Confidence in abilities
Pilot3_lngconf=reshape(volbank3,
                   varying = c( "vol2_conf","vol5_conf","vol6_conf","vol7_conf","vol13_conf","vol16_conf","vol18_conf","vol19_conf","vol20_conf", "vol22_conf"), v.names=c("conf"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp2", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp13", "vol_opp16", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp22"), new.row.names = 1:880, direction ="long")

#Combine all the repeated measures into one dataframe
volbank3_lng=data.frame(
  Sub_ID=Pilot3_lngtm1$Sub_ID,
  Vol_Opp=Pilot3_lngtm1$Vol_Opp,
  likely=Pilot3_lnglik$likely,
  tm1=Pilot3_lngtm1$tm1,
  tm2=Pilot3_lngtm2$tm2,
  tm3=Pilot3_lngtm3$tm3,
  sm1=Pilot3_lngsm1$sm1,
  sm2=Pilot3_lngsm2$sm2,
  sm3=Pilot3_lngsm3$sm3,
  difficult=Pilot3_lngdiff$difficult,
  confidence=Pilot3_lngconf$conf,
  Age=Pilot3_lngtm1$age)
volbank3_lng$Vol_Opp_num=Recode(volbank3_lng$Vol_Opp, "'vol_opp1'='1';
                              'vol_opp2'='2';
                              'vol_opp3'='3';
                              'vol_opp4'='4';
                              'vol_opp5'='5';
                              'vol_opp6'='6';
                              'vol_opp7'='7';
                              'vol_opp8'='8';
                              'vol_opp9'='9';
                              'vol_opp10'='10';
                              'vol_opp11'='11';
                              'vol_opp12'='12';
                              'vol_opp13'='13';
                              'vol_opp14'='14';
                              'vol_opp15'='15';
                              'vol_opp16'='16';
                              'vol_opp17'='17';
                              'vol_opp18'='18';
                              'vol_opp19'='19';
                              'vol_opp20'='20';
                              'vol_opp21'='21';
                              'vol_opp22'='22';", 
                              as.factor.result=F, as.numeric.result=T)

## set a factor for volunteer opportunity (vol_opp)
volbank3_lng$Vol_Opp=as.factor(volbank3_lng$Vol_Opp_num)
```

```{r correlation matrix}


```


```{r Cronbachs_alphas tm and sm}

#Cronbach's alpha tm
tm_alpha=as.matrix(cor(cbind(volbank3_lng$tm1, volbank3_lng$tm2, volbank3_lng$tm3), use="pairwise.complete.obs"))
row.names(tm_alpha)=(c("tm1", "tm2", "tm3"))
colnames(tm_alpha)=(c("tm1", "tm2", "tm3"))
summary(alpha(tm_alpha)) # -> alpha=0.9

#Cronbach's alpha sm
sm_alpha=as.matrix(cor(cbind(volbank3_lng$sm1, volbank3_lng$sm2, volbank3_lng$sm3), use="pairwise.complete.obs"))
row.names(sm_alpha)=(c("sm1", "sm2", "sm3"))
colnames(sm_alpha)=(c("sm1", "sm2", "sm3"))
summary(alpha(sm_alpha)) # -> alpha=0.81

#Combined mattering alpha
mtr_all_alpha=as.matrix(cor(cbind(volbank3_lng$tm1, volbank3_lng$tm2, volbank3_lng$tm3, volbank3_lng$sm1, volbank3_lng$sm2, volbank3_lng$sm3), use="pairwise.complete.obs"))
row.names(mtr_all_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
colnames(mtr_all_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
summary(alpha(mtr_all_alpha)) #-> combined alpha=0.9
cor.plot(mtr_all_alpha)
ggcorr(volbank3_lng[,4:9], label=T, label_alpha = F)#-> Gives us essentially the same plot as above. But I am also interested in seeing how the correlstions are correlated with one another.
ggcorr(mtr_all_alpha, label=T, label_alpha = F)#-> by calling the function on the correlation matrix, to my understanding I generate a plot of correlations of Pearson's Rs. Taken together with the previous results, it appears that while all the mtring items are positively correlated with one another, the pattern is such that sm2 and sm3 have similar relationships, but their relationships with the other items are neagatively correlated with those items relationships with one another.
```

I am a little worried that looking at alpha in the long form dataset infltates it a little bit due to similarity in responses that originates from the stimuli rather than from conceptual similarity between items...

```{r scale means}
## In the long-form dataset ##
#tm
volbank3_lng$tm_av=scale.means(volbank3_lng, "tm1", "tm2", "tm3", na.rm = F)
#sm
volbank3_lng$sm_av=scale.means(volbank3_lng, "sm1", "sm2", "sm3", na.rm = T)

## In the wide form dataset- per vol_opp ##
#Vol 2
volbank3$vol2_tm_av=scale.means(volbank3, "vol2_tm1", "vol2_tm2", "vol2_tm3", na.rm = F)
volbank3$vol2_sm_av=scale.means(volbank3, "vol2_sm1", "vol2_sm2", "vol2_sm3", na.rm = T)

#Vol 13
volbank3$vol13_tm_av=scale.means(volbank3, "vol13_tm1", "vol13_tm2", "vol13_tm3", na.rm = F)
volbank3$vol13_sm_av=scale.means(volbank3, "vol13_sm1", "vol13_sm2", "vol13_sm3", na.rm = T)

#Vol 22
volbank3$vol22_tm_av=scale.means(volbank3, "vol22_tm1", "vol22_tm2", "vol22_tm3", na.rm = F)
volbank3$vol22_sm_av=scale.means(volbank3, "vol22_sm1", "vol22_sm2", "vol22_sm3", na.rm = T)

#Vol 20
volbank3$vol20_tm_av=scale.means(volbank3, "vol20_tm1", "vol20_tm2", "vol20_tm3", na.rm = F)
volbank3$vol20_sm_av=scale.means(volbank3, "vol20_sm1", "vol20_sm2", "vol20_sm3", na.rm = T)

#Vol 7
volbank3$vol7_tm_av=scale.means(volbank3, "vol7_tm1", "vol7_tm2", "vol7_tm3", na.rm = F)
volbank3$vol7_sm_av=scale.means(volbank3, "vol7_sm1", "vol7_sm2", "vol7_sm3", na.rm = T)

#Vol 19
volbank3$vol19_tm_av=scale.means(volbank3, "vol19_tm1", "vol19_tm2", "vol19_tm3", na.rm = F)
volbank3$vol19_sm_av=scale.means(volbank3, "vol19_sm1", "vol19_sm2", "vol19_sm3", na.rm = T)

#Vol 18
volbank3$vol18_tm_av=scale.means(volbank3, "vol18_tm1", "vol18_tm2", "vol18_tm3", na.rm = F)
volbank3$vol18_sm_av=scale.means(volbank3, "vol18_sm1", "vol18_sm2", "vol18_sm3", na.rm = T)

#Vol 5
volbank3$vol5_tm_av=scale.means(volbank3, "vol5_tm1", "vol5_tm2", "vol5_tm3", na.rm = F)
volbank3$vol5_sm_av=scale.means(volbank3, "vol5_sm1", "vol5_sm2", "vol5_sm3", na.rm = T)

#Vol 6
volbank3$vol6_tm_av=scale.means(volbank3, "vol6_tm1", "vol6_tm2", "vol6_tm3", na.rm = F)
volbank3$vol6_sm_av=scale.means(volbank3, "vol6_sm1", "vol6_sm2", "vol6_sm3", na.rm = T)

# Vol 16
volbank3$vol16_tm_av=scale.means(volbank3, "vol16_tm1", "vol16_tm2", "vol16_tm3", na.rm = F)
volbank3$vol16_sm_av=scale.means(volbank3, "vol16_sm1", "vol16_sm2", "vol16_sm3", na.rm = T)
```


```{r plots}
#factor re-ordering occording to matchings
volbank3_lng$order=Recode(volbank3_lng$Vol_Opp, "
                        '2'='0.2';
                        '13'='1.13';
                        '22'='2.22';
                        '20'='3.20';
                        '7'='4.7';
                        '19'='5.19';
                        '18'='6.18';
                        '5'='7.5';
                        '6'='8.6';
                        '16'='9.16';", as.factor.result=T)


#tm scores
ggplot(volbank3_lng, aes(x=order, y=tm_av, fill=Vol_Opp))+
  stat_summary(fun.y="mean", geom="bar", position="dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar",
         position = position_dodge(width = 0.90), width = 0.2, fun.args = list(mult=1))+
      labs(x = "Volunteer Opportunity", y = "Target Mattering Score")
#Standerdized tm scores
ggplot(volbank3_lng, aes(x=order, y=scale(tm_av), fill=Vol_Opp))+
  stat_summary(fun.y="mean", geom="bar", position="dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar",
         position = position_dodge(width = 0.90), width = 0.2, fun.args = list(mult=1)) +
      labs(x = "Volunteer Opportunity", y = "Standerdized Target Mattering Score")+ggtitle("Pilot3 Std. TM scores (final 10)")

```

```{r t-tests for differences between matched opps}
#comparing opp 2 and opp 13 (cause match)##
#tm
print(t.test(volbank3$vol2_tm_av, volbank3$vol13_tm_av, paired = T)) # no difference
#sm
print(t.test(volbank3$vol2_sm_av, volbank3$vol13_sm_av, paired = T)) # no difference
#likely
print(t.test(volbank3$vol2_likely, volbank3$vol13_likely, paired = T)) # no difference ("trend" towards 13 more likely?)
#difficult
print(t.test(volbank3$vol2_diff, volbank3$vol13_diff, paired = T)) # yes- 13 more difficult
#Competence
print(t.test(volbank3$vol2_conf, volbank3$vol13_conf, paired=T)) # yes- people overall feel more confident in their ability to perform well in vol 2

##comparing opp 5 and opp 18 (cause match)##
#tm
print(t.test(volbank3$vol5_tm_av, volbank3$vol18_tm_av, paired = T)) # 18 higher tm
#sm
print(t.test(volbank3$vol5_sm_av, volbank3$vol18_sm_av, paired = T)) # no difference
#likely
print(t.test(volbank3$vol5_likely, volbank3$vol18_likely, paired = T)) # 18 significantly more likely
#difficult
print(t.test(volbank3$vol5_diff, volbank3$vol18_diff, paired = T)) # 18 significantly more difficult
#Competance
print(t.test(volbank3$vol5_conf, volbank3$vol18_conf, paired = T))

##Comparing opp 5 and opp 6 (work match)##
#tm
print(t.test(volbank3$vol5_tm_av, volbank3$vol6_tm_av, paired = T)) # 6 significantly higher tm
#sm
print(t.test(volbank3$vol5_sm_av, volbank3$vol6_sm_av, paired = T)) # No difference (trend towards 6 higer sm).
#likely
print(t.test(volbank3$vol5_likely, volbank3$vol6_likely, paired = T)) # no difference
#difficult
print(t.test(volbank3$vol5_diff, volbank3$vol6_diff, paired = T)) # no difference
#Competance
print(t.test(volbank3$vol5_conf, volbank3$vol6_conf, paired=T)) # no difference

##Comparing opp 6 and opp 16 (cause match)##
#tm
print(t.test(volbank3$vol6_tm_av, volbank3$vol16_tm_av, paired = T)) # 16 significantly higher tm
#sm
print(t.test(volbank3$vol6_sm_av, volbank3$vol16_sm_av, paired = T)) # 16 significanlty higer sm
#likely
print(t.test(volbank3$vol6_likely, volbank3$vol16_likely, paired = T)) # no difference, trend towards 16 more likely
#difficult
print(t.test(volbank3$vol6_diff, volbank3$vol16_diff, paired = T)) # 16 significantly more difficult
#Competance
print(t.test(volbank3$vol6_conf, volbank3$vol16_conf, paired=T)) #no difference

##Comparing opp 7 and opp 19 (cause match)##
#tm
print(t.test(volbank3$vol7_tm_av, volbank3$vol19_tm_av, paired = T)) # no difference
#sm
print(t.test(volbank3$vol7_sm_av, volbank3$vol19_sm_av, paired = T)) # no difference
#likely
print(t.test(volbank3$vol7_likely, volbank3$vol19_likely, paired = T)) # no difference
#difficult
print(t.test(volbank3$vol7_diff, volbank3$vol19_diff, paired = T)) # no difference
#Competance
print(t.test(volbank3$vol7_conf, volbank3$vol19_conf, paired = T)) #higher compatence vol 7 (p=0.046).

##Comparing opp 7 and opp 20 (work match)##
#tm
print(t.test(volbank3$vol7_tm_av, volbank3$vol20_tm_av, paired = T)) # 7 significanlty higher tm
#sm
print(t.test(volbank3$vol7_sm_av, volbank3$vol20_sm_av, paired = T)) # no difference
#likely
print(t.test(volbank3$vol7_likely, volbank3$vol20_likely, paired = T)) # no difference
#difficult
print(t.test(volbank3$vol7_diff, volbank3$vol20_diff, paired = T)) # 7 significantly more difficult
#Competence
print(t.test(volbank3$vol7_conf, volbank3$vol20_conf, paired = T)) #no difference (trend towards 20 higher conf p=0.085)

##Comparing opp 13 and opp 22 (work match)##
#tm
print(t.test(volbank3$vol13_tm_av, volbank3$vol22_tm_av, paired = T)) # 22 significatly higher tm
#sm
print(t.test(volbank3$vol13_sm_av, volbank3$vol22_sm_av, paired = T)) # 22 significantly higher sm
#likely
print(t.test(volbank3$vol13_likely, volbank3$vol22_likely, paired = T)) # 22 significanlty more likely.
#difficult
print(t.test(volbank3$vol13_diff, volbank3$vol22_diff, paired = T)) # 13 significantly more difficult
#Competence
print(t.test(volbank3$vol13_conf, volbank3$vol22_conf, paired = T)) # 22 significantly higher conf

##Comparing opp 18 and opp 19 (work match)##
#tm
print(t.test(volbank3$vol18_tm_av, volbank3$vol19_tm_av, paired = T)) # 19 significatly higher tm
#sm
print(t.test(volbank3$vol18_sm_av, volbank3$vol19_sm_av, paired = T)) # 19 significantly higher sm
#likely
print(t.test(volbank3$vol18_likely, volbank3$vol19_likely, paired = T)) # 19 significanlty more likely (p=0.025).
#difficult
print(t.test(volbank3$vol18_diff, volbank3$vol19_diff, paired = T)) # no difference
#Competence
print(t.test(volbank3$vol18_conf, volbank3$vol19_conf, paired = T)) #no difference

##Comparing opp 20 and opp 22 (cause match- weak)##
#tm
print(t.test(volbank3$vol20_tm_av, volbank3$vol22_tm_av, paired = T)) # no difference
#sm
print(t.test(volbank3$vol20_sm_av, volbank3$vol22_sm_av, paired = T)) # 20 significantly higher sm
#likely
print(t.test(volbank3$vol20_likely, volbank3$vol22_likely, paired = T)) # 20 significanlty more likely.
#difficult
print(t.test(volbank3$vol20_diff, volbank3$vol22_diff, paired = T)) # no difference
#Competence
print(t.test(volbank3$vol20_conf, volbank3$vol22_conf, paired=T)) # 20 significantly higher conf

```

```{r power analysis}
#What is the power of the t.test to detect tm scores difference


```
