---
title: "Volunteer_Bank_Pilot"
author: "Yochai Shavit"
date: "July 27, 2016"
output: html_document
---

```{r load packages}
library(knitr)
library(ggplot2)
library(car)
library(psych)
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)

```

```{r load data}
getwd()
setwd("C:/Users/Yochai/Documents/Stanford Ph.D/Volunteer studies data/Volunteer opportunities bank and survey/Volunteer_Bank_Pilot")
Pilot1=read.csv("VolunteerBank_Pilot1.csv")
Pilot1$Sub_ID=as.factor((Pilot1$Sub_ID))
```
 
```{r long form data}
#Long-form repeated measures variables

#Likely
Pilot1_lnglik=reshape(Pilot1,
                   varying = c("vol1_likely", "vol2_likely","vol3_likely","vol4_likely","vol5_likely","vol6_likely","vol7_likely","vol8_likely","vol9_likely","vol10_likely","vol11_likely","vol12_likely","vol13_likely","vol14_likely","vol15_likely","vol16_likely","vol17_likely","vol18_likely","vol19_likely","vol20_likely","vol21_likely", "vol22_likely"), v.names=c("likely"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm1
Pilot1_lngtm1=reshape(Pilot1,
                   varying = c("vol1_tm1", "vol2_tm1", "vol3_tm1", "vol4_tm1", "vol5_tm1", "vol6_tm1","vol7_tm1","vol8_tm1","vol9_tm1","vol10_tm1","vol11_tm1","vol12_tm1","vol13_tm1","vol14_tm1","vol15_tm1","vol16_tm1","vol17_tm1","vol18_tm1","vol19_tm1","vol20_tm1","vol21_tm1", "vol22_tm1"), v.names=c("tm1"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm2
Pilot1_lngtm2=reshape(Pilot1,
                   varying = c("vol1_tm2", "vol2_tm2", "vol3_tm2", "vol4_tm2", "vol5_tm2", "vol6_tm2","vol7_tm2","vol8_tm2","vol9_tm2","vol10_tm2","vol11_tm2","vol12_tm2","vol13_tm2","vol14_tm2","vol15_tm2","vol16_tm2","vol17_tm2","vol18_tm2","vol19_tm2","vol20_tm2","vol21_tm2", "vol22_tm2"), v.names=c("tm2"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#tm3
Pilot1_lngtm3=reshape(Pilot1,
                   varying = c("vol1_tm3", "vol2_tm3", "vol3_tm3", "vol4_tm3", "vol5_tm3", "vol6_tm3","vol7_tm3","vol8_tm3","vol9_tm3","vol10_tm3","vol11_tm3","vol12_tm3","vol13_tm3","vol14_tm3","vol15_tm3","vol16_tm3","vol17_tm3","vol18_tm3","vol19_tm3","vol20_tm3","vol21_tm3", "vol22_tm3"), v.names=c("tm3"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm1
Pilot1_lngsm1=reshape(Pilot1,
                   varying = c("vol1_sm1", "vol2_sm1", "vol3_sm1", "vol4_sm1", "vol5_sm1", "vol6_sm1","vol7_sm1","vol8_sm1","vol9_sm1","vol10_sm1","vol11_sm1","vol12_sm1","vol13_sm1","vol14_sm1","vol15_sm1","vol16_sm1","vol17_sm1","vol18_sm1","vol19_sm1","vol20_sm1","vol21_sm1", "vol22_sm1"), v.names=c("sm1"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm2
Pilot1_lngsm2=reshape(Pilot1,
                   varying = c("vol1_sm2", "vol2_sm2", "vol3_sm2", "vol4_sm2", "vol5_sm2", "vol6_sm2","vol7_sm2","vol8_sm2","vol9_sm2","vol10_sm2","vol11_sm2","vol12_sm2","vol13_sm2","vol14_sm2","vol15_sm2","vol16_sm2","vol17_sm2","vol18_sm2","vol19_sm2","vol20_sm2","vol21_sm2", "vol22_sm2"), v.names=c("sm2"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#sm3
Pilot1_lngsm3=reshape(Pilot1,
                   varying = c("vol1_sm3", "vol2_sm3", "vol3_sm3", "vol4_sm3", "vol5_sm3", "vol6_sm3","vol7_sm3","vol8_sm3","vol9_sm3","vol10_sm3","vol11_sm3","vol12_sm3","vol13_sm3","vol14_sm3","vol15_sm3","vol16_sm3","vol17_sm3","vol18_sm3","vol19_sm3","vol20_sm3","vol21_sm3", "vol22_sm3"), v.names=c("sm3"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#Difficulty
Pilot1_lngdiff=reshape(Pilot1,
                   varying = c("vol1_diff", "vol2_diff","vol3_diff","vol4_diff","vol5_diff","vol6_diff","vol7_diff","vol8_diff","vol9_diff","vol10_diff","vol11_diff","vol12_diff","vol13_diff","vol14_diff","vol15_diff","vol16_diff","vol17_diff","vol18_diff","vol19_diff","vol20_diff","vol21_diff", "vol22_diff"), v.names=c("difficult"), timevar = "Vol_Opp", idvar = "Sub_ID", ids=1:40, times=c("vol_opp1","vol_opp2", "vol_opp3", "vol_opp4", "vol_opp5", "vol_opp6", "vol_opp7", "vol_opp8", "vol_opp9", "vol_opp10", "vol_opp11", "vol_opp12", "vol_opp13", "vol_opp14", "vol_opp15", "vol_opp16", "vol_opp17", "vol_opp18", "vol_opp19", "vol_opp20", "vol_opp21", "vol_opp22"), new.row.names = 1:880, direction ="long")

#Combine all the repeated measures into one dataframe
Pilot1_lng=data.frame(
  Sub_ID=Pilot1_lngtm1$Sub_ID,
  Vol_Opp=Pilot1_lngtm1$Vol_Opp,
  likely=Pilot1_lnglik$likely,
  tm1=Pilot1_lngtm1$tm1,
  tm2=Pilot1_lngtm2$tm2,
  tm3=Pilot1_lngtm3$tm3,
  sm1=Pilot1_lngsm1$sm1,
  sm2=Pilot1_lngsm2$sm2,
  sm3=Pilot1_lngsm3$sm3,
  difficult=Pilot1_lngdiff$difficult,
  Age=Pilot1_lngtm1$Age)
Pilot1_lng$Vol_Opp_num=recode(Pilot1_lng$Vol_Opp, "'vol_opp1'='1';
                              'vol_opp2'='2';
                              'vol_opp3'='3';
                              'vol_opp4'='4';
                              'vol_opp5'='5';
                              'vol_opp6'='6';
                              'vol_opp7'='7';
                              'vol_opp8'='8';
                              'vol_opp9'='9';
                              'vol_opp10'='10';
                              'vol_opp11'='11';
                              'vol_opp12'='12';
                              'vol_opp13'='13';
                              'vol_opp14'='14';
                              'vol_opp15'='15';
                              'vol_opp16'='16';
                              'vol_opp17'='17';
                              'vol_opp18'='18';
                              'vol_opp19'='19';
                              'vol_opp20'='20';
                              'vol_opp21'='21';
                              'vol_opp22'='22';", 
                              as.factor.result=F, as.numeric.result=T)

```

```{r Cronbach's alphas}
#Mattering items across all volunteer opportnities
tm_alpha=as.matrix(cor(cbind(Pilot1_lng$tm1, Pilot1_lng$tm2, Pilot1_lng$tm3), use="pairwise.complete.obs"))
row.names(tm_alpha)=(c("tm1", "tm2", "tm3"))
colnames(tm_alpha)=(c("tm1", "tm2", "tm3"))
summary(alpha(tm_alpha)) #-> 0.95

sm_alpha=as.matrix(cor(cbind(Pilot1_lng$sm1, Pilot1_lng$sm2, Pilot1_lng$sm3), use="pairwise.complete.obs"))
row.names(sm_alpha)=(c("sm1", "sm2", "sm3"))
colnames(sm_alpha)=(c("sm1", "sm2", "sm3"))
summary(alpha(sm_alpha)) #-> 0.8

tsm_alpha=as.matrix(cor(cbind(Pilot1_lng$sm1, Pilot1_lng$sm2, Pilot1_lng$sm3,Pilot1_lng$tm1, Pilot1_lng$tm2, Pilot1_lng$tm3), use="pairwise.complete.obs"))
row.names(tsm_alpha)=(c("sm1", "sm2", "sm3", "tm1", "tm2", "tm3"))
colnames(tsm_alpha)=(c("sm1", "sm2", "sm3", "tm1", "tm2", "tm3"))
summary(alpha(tsm_alpha)) #->0.9

#Vol_1
vol1_alpha=as.matrix(cor(cbind(Pilot1$vol1_tm1, Pilot1$vol1_tm2, Pilot1$vol1_tm3, Pilot1$vol1_sm1, Pilot1$vol1_sm2, Pilot1$vol1_sm3),use="pairwise.complete.obs"))
row.names(vol1_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
colnames(vol1_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
summary(alpha(vol1_alpha, check.keys = T)) #-> 0.94 with just tm, 0.93 tm+sm

#vol_2
vol2_alpha=as.matrix(cor(cbind(Pilot1$vol2_tm1, Pilot1$vol2_tm2, Pilot1$vol2_tm3, Pilot1$vol2_sm1, Pilot1$vol2_sm2, Pilot1$vol2_sm3),use="pairwise.complete.obs"))
row.names(vol2_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
colnames(vol2_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
summary(alpha(vol2_alpha, check.keys = T)) #-> 0.97 with just tm, 0.91 tm+sm

#Vol_3
vol3_alpha=as.matrix(cor(cbind(Pilot1$vol3_tm1, Pilot1$vol3_tm2, Pilot1$vol3_tm3,Pilot1$vol3_sm1, Pilot1$vol3_sm2, Pilot1$vol3_sm3),use="pairwise.complete.obs"))
row.names(vol3_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
colnames(vol3_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
summary(alpha(vol3_alpha, check.keys = T)) #-> 0.92 with just tm, 0.65 tm+sm (sm2 & sm3 are negatively correlated with the scale)

#Vol_4
vol4_alpha=as.matrix(cor(cbind(Pilot1$vol4_tm1, Pilot1$vol4_tm2, Pilot1$vol4_tm3),use="pairwise.complete.obs"))
row.names(vol4_alpha)=(c("tm1", "tm2", "tm3"))
colnames(vol4_alpha)=(c("tm1", "tm2", "tm3"))
summary(alpha(vol4_alpha, check.keys = T)) #-> 0.91 with just tm, 0.77 tm+sm (sm3 negatively correlated)

#Vol_5
vol5_alpha=as.matrix(cor(cbind(Pilot1$vol5_tm1, Pilot1$vol5_tm2, Pilot1$vol5_tm3, Pilot1$vol5_sm1, Pilot1$vol5_sm2, Pilot1$vol5_sm3),use="pairwise.complete.obs"))
row.names(vol5_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
colnames(vol5_alpha)=(c("tm1", "tm2", "tm3", "sm1", "sm2", "sm3"))
summary(alpha(vol5_alpha, check.keys = T)) #-> 0.92 with just tm, 0.91 with sm
```

```{r standerdized tm scores}
#Create a valuesof average tm across the three items
x1=mean(na.omit(c(Pilot1$vol1_tm1, Pilot1$vol1_tm2, Pilot1$vol1_tm3)))
sd1=sd(na.omit(c(Pilot1$vol1_tm1, Pilot1$vol1_tm2, Pilot1$vol1_tm3)))
x2=mean(na.omit(c(Pilot1$vol2_tm1, Pilot1$vol2_tm2, Pilot1$vol2_tm3)))
sd2=sd(na.omit(c(Pilot1$vol2_tm1, Pilot1$vol2_tm2, Pilot1$vol2_tm3)))
x3=mean(na.omit(c(Pilot1$vol3_tm1, Pilot1$vol3_tm2, Pilot1$vol3_tm3)))
sd3=sd(na.omit(c(Pilot1$vol3_tm1, Pilot1$vol3_tm2, Pilot1$vol3_tm3)))
x4=mean(na.omit(c(Pilot1$vol4_tm1, Pilot1$vol4_tm2, Pilot1$vol4_tm3)))
sd4=sd(na.omit(c(Pilot1$vol4_tm1, Pilot1$vol4_tm2, Pilot1$vol4_tm3)))
x5=mean(na.omit(c(Pilot1$vol5_tm1, Pilot1$vol5_tm2, Pilot1$vol5_tm3)))
sd5=sd(na.omit(c(Pilot1$vol5_tm1, Pilot1$vol5_tm2, Pilot1$vol5_tm3)))
x6=mean(na.omit(c(Pilot1$vol6_tm1, Pilot1$vol6_tm2, Pilot1$vol6_tm3)))
sd6=sd(na.omit(c(Pilot1$vol6_tm1, Pilot1$vol6_tm2, Pilot1$vol6_tm3)))
x7=mean(na.omit(c(Pilot1$vol7_tm1, Pilot1$vol7_tm2, Pilot1$vol7_tm3)))
sd7=sd(na.omit(c(Pilot1$vol7_tm1, Pilot1$vol7_tm2, Pilot1$vol7_tm3)))
x8=mean(na.omit(c(Pilot1$vol8_tm1, Pilot1$vol8_tm2, Pilot1$vol8_tm3)))
sd8=sd(na.omit(c(Pilot1$vol8_tm1, Pilot1$vol8_tm2, Pilot1$vol8_tm3)))
x9=mean(na.omit(c(Pilot1$vol9_tm1, Pilot1$vol9_tm2, Pilot1$vol9_tm3)))
sd9=sd(na.omit(c(Pilot1$vol9_tm1, Pilot1$vol9_tm2, Pilot1$vol9_tm3)))
x10=mean(na.omit(c(Pilot1$vol10_tm1, Pilot1$vol10_tm2, Pilot1$vol10_tm3)))
sd10=sd(na.omit(c(Pilot1$vol10_tm1, Pilot1$vol10_tm2, Pilot1$vol10_tm3)))
x11=mean(na.omit(c(Pilot1$vol11_tm1, Pilot1$vol11_tm2, Pilot1$vol11_tm3)))
sd11=sd(na.omit(c(Pilot1$vol11_tm1, Pilot1$vol11_tm2, Pilot1$vol11_tm3)))
x12=mean(na.omit(c(Pilot1$vol12_tm1, Pilot1$vol12_tm2, Pilot1$vol12_tm3)))
sd12=sd(na.omit(c(Pilot1$vol12_tm1, Pilot1$vol12_tm2, Pilot1$vol12_tm3)))
x13=mean(na.omit(c(Pilot1$vol13_tm1, Pilot1$vol13_tm2, Pilot1$vol13_tm3)))
sd13=sd(na.omit(c(Pilot1$vol13_tm1, Pilot1$vol13_tm2, Pilot1$vol13_tm3)))
x14=mean(na.omit(c(Pilot1$vol14_tm1, Pilot1$vol14_tm2, Pilot1$vol14_tm3)))
sd14=sd(na.omit(c(Pilot1$vol14_tm1, Pilot1$vol14_tm2, Pilot1$vol14_tm3)))
x15=mean(na.omit(c(Pilot1$vol15_tm1, Pilot1$vol15_tm2, Pilot1$vol15_tm3)))
sd15=sd(na.omit(c(Pilot1$vol15_tm1, Pilot1$vol15_tm2, Pilot1$vol15_tm3)))
x16=mean(na.omit(c(Pilot1$vol16_tm1, Pilot1$vol16_tm2, Pilot1$vol16_tm3)))
sd16=sd(na.omit(c(Pilot1$vol16_tm1, Pilot1$vol16_tm2, Pilot1$vol16_tm3)))
x17=mean(na.omit(c(Pilot1$vol17_tm1, Pilot1$vol17_tm2, Pilot1$vol17_tm3)))
sd17=sd(na.omit(c(Pilot1$vol17_tm1, Pilot1$vol17_tm2, Pilot1$vol17_tm3)))
x18=mean(na.omit(c(Pilot1$vol18_tm1, Pilot1$vol18_tm2, Pilot1$vol18_tm3)))
sd18=sd(na.omit(c(Pilot1$vol18_tm1, Pilot1$vol18_tm2, Pilot1$vol18_tm3)))
x19=mean(na.omit(c(Pilot1$vol19_tm1, Pilot1$vol19_tm2, Pilot1$vol19_tm3)))
sd19=sd(na.omit(c(Pilot1$vol19_tm1, Pilot1$vol19_tm2, Pilot1$vol19_tm3)))
x20=mean(na.omit(c(Pilot1$vol20_tm1, Pilot1$vol20_tm2, Pilot1$vol20_tm3)))
sd20=sd(na.omit(c(Pilot1$vol20_tm1, Pilot1$vol20_tm2, Pilot1$vol20_tm3)))
x21=mean(na.omit(c(Pilot1$vol21_tm1, Pilot1$vol21_tm2, Pilot1$vol21_tm3)))
sd21=sd(na.omit(c(Pilot1$vol21_tm1, Pilot1$vol21_tm2, Pilot1$vol21_tm3)))
x22=mean(na.omit(c(Pilot1$vol22_tm1, Pilot1$vol22_tm2, Pilot1$vol22_tm3)))
sd22=sd(na.omit(c(Pilot1$vol22_tm1, Pilot1$vol22_tm2, Pilot1$vol22_tm3)))
  
#combine all scores into single variable in Pilot1_lng
Pilot1_lng$tm_av_vol=ifelse(Pilot1_lng$Vol_Opp_num==1, x1, ifelse(Pilot1_lng$Vol_Opp_num==2, x2, ifelse(Pilot1_lng$Vol_Opp_num==3, x3,ifelse(Pilot1_lng$Vol_Opp_num==4, x4, ifelse(Pilot1_lng$Vol_Opp_num==5, x5, ifelse(Pilot1_lng$Vol_Opp_num==6, x6, ifelse(Pilot1_lng$Vol_Opp_num==7, x7,ifelse(Pilot1_lng$Vol_Opp_num==8, x8, ifelse(Pilot1_lng$Vol_Opp_num==9, x9,ifelse(Pilot1_lng$Vol_Opp_num==10, x10,ifelse(Pilot1_lng$Vol_Opp_num==11, x11,ifelse(Pilot1_lng$Vol_Opp_num==12, x12,ifelse(Pilot1_lng$Vol_Opp_num==13, x13,ifelse(Pilot1_lng$Vol_Opp_num==14, x14,ifelse(Pilot1_lng$Vol_Opp_num==15, x15, ifelse(Pilot1_lng$Vol_Opp_num==16, x16, ifelse(Pilot1_lng$Vol_Opp_num==17, x17,ifelse(Pilot1_lng$Vol_Opp_num==18, x18,ifelse(Pilot1_lng$Vol_Opp_num==19, x19, ifelse(Pilot1_lng$Vol_Opp_num==20, x20,ifelse(Pilot1_lng$Vol_Opp_num==21, x21, x22)))))))))))))))))))))

#Do the same for S.D's
Pilot1_lng$tm_sd_vol=ifelse(Pilot1_lng$Vol_Opp_num==1, sd1, ifelse(Pilot1_lng$Vol_Opp_num==2, sd2, ifelse(Pilot1_lng$Vol_Opp_num==3, sd3,ifelse(Pilot1_lng$Vol_Opp_num==4, sd4, ifelse(Pilot1_lng$Vol_Opp_num==5, sd5, ifelse(Pilot1_lng$Vol_Opp_num==6, sd6, ifelse(Pilot1_lng$Vol_Opp_num==7, sd7,ifelse(Pilot1_lng$Vol_Opp_num==8, sd8, ifelse(Pilot1_lng$Vol_Opp_num==9, sd9,ifelse(Pilot1_lng$Vol_Opp_num==10, sd10,ifelse(Pilot1_lng$Vol_Opp_num==11, sd11,ifelse(Pilot1_lng$Vol_Opp_num==12, sd12,ifelse(Pilot1_lng$Vol_Opp_num==13, sd13,ifelse(Pilot1_lng$Vol_Opp_num==14, sd14,ifelse(Pilot1_lng$Vol_Opp_num==15, sd15, ifelse(Pilot1_lng$Vol_Opp_num==16, sd16, ifelse(Pilot1_lng$Vol_Opp_num==17, sd17,ifelse(Pilot1_lng$Vol_Opp_num==18, sd18,ifelse(Pilot1_lng$Vol_Opp_num==19, sd19, ifelse(Pilot1_lng$Vol_Opp_num==20, sd20,ifelse(Pilot1_lng$Vol_Opp_num==21, sd21, sd22)))))))))))))))))))))

#Create a varaible in Pilot1_lng of standerdized scores
Pilot1_lng$tm_z_vol=scale(Pilot1_lng$tm_av_vol)
is.numeric(Pilot1_lng$tm_z_vol)
Pilot1_lng$tm_sd_z_vol=scale(Pilot1_lng$tm_sd_vol)
is.numeric(Pilot1_lng$tm_sd_z_vol)

ggplot(data=Pilot1_lng, aes(x=Vol_Opp, y=tm_z_vol, fill=Vol_Opp))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Volunteer Opportunity", y = "Standerdized Target Mattering Score")

ggplot(data=Pilot1_lng, aes(x=Vol_Opp, y=tm_sd_vol, fill=Vol_Opp))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Volunteer Opportunity", y = "S.D of Target Mattering Score")

###########################################################################

#Option 2- create a standerdized tm score based on differences between participants

#Step 1: create a varaible for each vol_opp's tm
Pilot1$tm_av_vol1=(Pilot1$vol1_tm1+Pilot1$vol1_tm2+Pilot1$vol1_tm3)/3
Pilot1$tm_av_vol2=(Pilot1$vol2_tm1+Pilot1$vol2_tm2+Pilot1$vol2_tm3)/3
Pilot1$tm_av_vol3=(Pilot1$vol3_tm1+Pilot1$vol3_tm2+Pilot1$vol3_tm3)/3
Pilot1$tm_av_vol4=(Pilot1$vol4_tm1+Pilot1$vol4_tm2+Pilot1$vol4_tm3)/3
Pilot1$tm_av_vol5=(Pilot1$vol5_tm1+Pilot1$vol5_tm2+Pilot1$vol5_tm3)/3
Pilot1$tm_av_vol6=(Pilot1$vol6_tm1+Pilot1$vol6_tm2+Pilot1$vol6_tm3)/3
Pilot1$tm_av_vol7=(Pilot1$vol7_tm1+Pilot1$vol7_tm2+Pilot1$vol7_tm3)/3
Pilot1$tm_av_vol8=(Pilot1$vol8_tm1+Pilot1$vol8_tm2+Pilot1$vol8_tm3)/3
Pilot1$tm_av_vol9=(Pilot1$vol9_tm1+Pilot1$vol9_tm2+Pilot1$vol9_tm3)/3
Pilot1$tm_av_vol10=(Pilot1$vol10_tm1+Pilot1$vol10_tm2+Pilot1$vol10_tm3)/3
Pilot1$tm_av_vol11=(Pilot1$vol11_tm1+Pilot1$vol11_tm2+Pilot1$vol11_tm3)/3
Pilot1$tm_av_vol12=(Pilot1$vol12_tm1+Pilot1$vol12_tm2+Pilot1$vol12_tm3)/3
Pilot1$tm_av_vol13=(Pilot1$vol13_tm1+Pilot1$vol13_tm2+Pilot1$vol13_tm3)/3
Pilot1$tm_av_vol14=(Pilot1$vol14_tm1+Pilot1$vol14_tm2+Pilot1$vol14_tm3)/3
Pilot1$tm_av_vol15=(Pilot1$vol15_tm1+Pilot1$vol15_tm2+Pilot1$vol15_tm3)/3
Pilot1$tm_av_vol16=(Pilot1$vol16_tm1+Pilot1$vol16_tm2+Pilot1$vol16_tm3)/3
Pilot1$tm_av_vol17=(Pilot1$vol17_tm1+Pilot1$vol17_tm2+Pilot1$vol17_tm3)/3
Pilot1$tm_av_vol18=(Pilot1$vol18_tm1+Pilot1$vol18_tm2+Pilot1$vol18_tm3)/3
Pilot1$tm_av_vol19=(Pilot1$vol19_tm1+Pilot1$vol19_tm2+Pilot1$vol19_tm3)/3
Pilot1$tm_av_vol20=(Pilot1$vol20_tm1+Pilot1$vol20_tm2+Pilot1$vol20_tm3)/3
Pilot1$tm_av_vol21=(Pilot1$vol21_tm1+Pilot1$vol21_tm2+Pilot1$vol21_tm3)/3
Pilot1$tm_av_vol22=(Pilot1$vol22_tm1+Pilot1$vol22_tm2+Pilot1$vol22_tm3)/3


#Plots
ggplot(data=Pilot1, aes(x=Sub_ID, y=tm_av_vol1, fill=Sub_ID))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Subject", y = " Opp. 1 Target Mattering Score")

ggplot(data=Pilot1, aes(x=Sub_ID, y=tm_av_vol2, fill=Sub_ID))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Subject", y = " Opp. 2 Target Mattering Score")

##################################################################

#Option 3- probably the best one- create a tm score in Pilot1_lng, based on invidual participants scores for each opportunity

Pilot1_lng$tm_av=(Pilot1_lng$tm1+Pilot1_lng$tm2+Pilot1_lng$tm3)/3
#Plot (should look like the plot from option 1 but with errorbars that make sense)
ggplot(data=Pilot1_lng, aes(x=Vol_Opp, y=scale(tm_av), fill=Vol_Opp))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Volunteer Opportunity", y = "Standerdized Target Mattering Score")
ggsave("Staderdized Mattering scores Pilot 1.png")

#Let's do the same thing with sm scores- I expected that error bars here would be much wider and that differences between vol_opps won't be so evident-> That's not the case

Pilot1_lng$sm_av=(Pilot1_lng$sm1+Pilot1_lng$sm2+Pilot1_lng$sm3)/3

ggplot(data=Pilot1_lng, aes(x=Vol_Opp, y=scale(sm_av), fill=Vol_Opp))+
 stat_summary(fun.y="mean", geom="bar", position = "dodge")+
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", mult=1,
         position = position_dodge(width = 0.90), width = 0.2) +
      labs(x = "Volunteer Opportunity", y = "Standerdized Self Mattering Score")

```

